export enum ScreenName {
  BrowserScreen = 'Browser',
  LinksTabNavigation = 'Links',
  LinksBookmarksScreen = 'Bookmarks',
  LinkHistoryScreen = 'History',
  SettingsStackNavigation = 'Settings Stack Navigation',
  SettingsScreen = 'Settings',
  SettingsNetworkScreen = 'Network',
  SettingsCurrencyScreen = 'Currency',
  SettingsSearchEngineScreen = 'Search Engine',
  SettingsBackupStackNavigation = 'Backup Stack Navigation',
  SettingsBackupScreen = 'Backup',
  SettingsBackupQuizScreen = 'Quiz',
  WalletImportStackNavigation = 'Wallet Import Stack Navigation',
  WalletImportScreen = 'Import Accounts',
  WalletImportAccountSelectorScreen = 'Choose Accounts',
  WalletReceiveScreen = 'Receive',
  WalletSendStackNavigation = 'Wallet Send Stack Navigation',
  WalletSendScreen = 'Send',
  WalletScanScreen = 'Scan',
  WalletSendConfirmScreen = 'Confirm',
  WalletTokenSearchScreen = 'Search Tokens',
}
