export enum ScreenName {
  BrowserScreen = 'Browser',
  LinksTabNavigation = 'Links',
  LinksBookmarksScreen = 'Bookmarks',
  LinkHistoryScreen = 'History',
  SettingsStackNavigation = 'Settings Stack',
  SettingsScreen = 'Settings',
  SettingsNetworkScreen = 'Network',
  SettingsCurrencyScreen = 'Currency',
  SettingsSearchEngineScreen = 'Search Engine',
  SettingsBackupScreen = 'Backup',
  SettingsBackupQuizScreen = 'Quiz',
  WalletImportStackNavigation = 'Wallet Import Stack',
  WalletImport = 'Import Accounts',
  WalletImportAccountSelector = 'Choose Accounts',
  WalletConfirm = 'Confirm',
  WalletReceive = 'Receive',
  WalletScan = 'Scan',
  WalletSend = 'Send',
  WalletTokenSearch = 'Search Tokens',
}
