# frozen_string_literal: true

platform :ios, '9.0'

target 'DappFace' do
  # https://github.com/invertase/react-native-firebase/issues/414#issuecomment-388135093
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'RCTImage'
  ]

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'Firebase/Core', '~> 6.3.0'

  pod 'GoogleIDFASupport', '~> 3.14.0'

  pod 'RNGestureHandler', path: '../node_modules/react-native-gesture-handler'

  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'

  pod 'RNFS', path: '../node_modules/react-native-fs'

  pod 'RNKeychain', path: '../node_modules/react-native-keychain'

  pod(
    'react-native-orientation',
    path: '../node_modules/react-native-orientation'
  )

  pod(
    'react-native-randombytes',
    path: '../node_modules/react-native-randombytes'
  )

  pod 'TouchID', path: '../node_modules/react-native-touch-id'

  pod 'RNVectorIcons', path: '../node_modules/react-native-vector-icons'

  pod(
    'react-native-splash-screen',
    path: '../node_modules/react-native-splash-screen'
  )

  pod 'Interactable', path: '../node_modules/react-native-interactable'

  pod 'react-native-webview', path: '../node_modules/react-native-webview'

  target 'DappFaceTests' do
    inherit! :search_paths
  end
end

# https://github.com/invertase/react-native-firebase/issues/414#issuecomment-388135093
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.remove_from_project if target.name == 'React'
    target.remove_from_project if target.name == 'yoga'
  end
end
