# frozen_string_literal: true

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'DappFace' do
  # Pods for DappFace
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Third Party Pods
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'
  pod(
    'react-native-orientation',
    :path => '../node_modules/react-native-orientation'
  )
  pod(
    'react-native-randombytes',
    :path => '../node_modules/react-native-randombytes'
  )
  pod 'TouchID', :path => '../node_modules/react-native-touch-id'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod(
    'react-native-splash-screen',
    :path => '../node_modules/react-native-splash-screen'
  )
  pod 'Interactable', :path => '../node_modules/react-native-interactable'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'DappFaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'DappFace-tvOS' do
  # Pods for DappFace-tvOS

  target 'DappFace-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
