name: Lint

on: push

jobs:
  javascript:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Switch node version
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: Install dependencies
        run: npm i
      - name: Check lint error
        run: npm run lint
  ruby:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Switch ruby version
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6.x"
      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          bundle install
      - name: Check lint error
        run: npm run lint:ruby
  typecheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Switch node version
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: Install dependencies
        run: npm i
      - name: Check type error
        run: npm run typecheck
