name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.16.3'
    - run: npm i
    - run: npm run lint
    
